<?php
echo '';
echo '<!DOCTYPE html>';
echo '<html lang="id">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<link rel="stylesheet" href="css/bootstrap.min.css">';
echo '<link rel="stylesheet" href="css/owl.carousel.min.css">';
echo '<link rel="stylesheet" href="css/owl.theme.default.min.css">';
echo '<link rel="stylesheet" href="css/jquery.paginate.css">';
echo '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />';
echo '<link rel="stylesheet" href="css/blog-togel.css?v=9">';
echo '<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />';
echo '<link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/dataTables.bootstrap5.min.css">';
echo '<link rel="icon" type="image/png" href="https://ik.imagekit.io/rwvgghdvd/LIMATOGEL/fav.png?updatedAt=1728374279114" sizes="192x192">';
echo '<link rel="apple-touch-icon" sizes="180x180" href="https://ik.imagekit.io/rwvgghdvd/LIMATOGEL/fav.png?updatedAt=1728374279114">';
echo '';
echo '<title>KELUHAN MEMBER</title>';
echo '<link rel="icon" type="image/png" href="https://ik.imagekit.io/rwvgghdvd/LIMATOGEL/fav.png?updatedAt=1728374279114" sizes="192x192">';
echo '<link rel="apple-touch-icon" sizes="180x180" href="https://ik.imagekit.io/rwvgghdvd/LIMATOGEL/fav.png?updatedAt=1728374279114">';
echo '<meta content='index, follow' name='robots'/>';
echo '<meta content='1 days' name='revisit-after'/>';
echo '<meta content='general' name='rating'/>';
echo '<meta content='id' name='geo.country'/>';
echo '<meta content='Indonesia' name='geo.placename'/>';
echo '<meta content='id' name='language'/>';
echo '<meta content='never' name='expires'/>';
echo '<meta content='ALL' name='SPIDERS'/>';
echo '<meta content='ALL' name='WEBCRAWLERS'/>';
echo '<meta content='always' name='revisit-after'/>';
echo '<meta content='global' name='distribution'/>';
echo '<meta content='milo4d' name='author'/>';
echo '<meta content='all' name='Slurp'/>';
echo '<link rel="icon" type="image/ico" href="https://ik.imagekit.io/rwvgghdvd/LIMATOGEL/fav.png?updatedAt=1728374279114" />';
echo '<link rel="canonical" href="/" />';
echo '<meta name="google-site-verification" content="4xvD1psmoCKXTyqQDJaEVkFbJpjkTlaYDDwsTyjV6Bw" />';
echo '<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>';
echo '<script src="js/jquery.paginate.js"></script>';
echo '';
echo '<style>';
echo 'body{';
echo 'background: url("https://ik.imagekit.io/rwvgghdvd/LIMATOGEL/background.jpg?updatedAt=1728105273272") !important;';
echo 'background-size: cover !important;';
echo 'background-attachment: fixed !important;';
echo 'background-position-x: center !important;';
echo 'background-position-y: center !important;';
echo '}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '';
echo '<div id="navmobile" class="sidenav d-lg-none">';
echo '<a href="javascript:void(0)" class="closebtn" onclick="clsMobilenav()">&times;</a>';
echo '<a class="home-m nav-m" href="/"> Home</a>';
echo '<a class="livedraw-m  nav-m" href="?page=livedraw-togel">Live draw</a>';
echo '<a class="prediksi-m  nav-m" href="?page=prediksi-mobile">Prediksi Togel</a>';
echo '<a class="promosi-m  nav-m" target="_blank" href="https://limalangit.com/promotion">Promosi</a>';
echo '<a class="data-m  nav-m" href="https://rtp-lima.com/lima" target="_blank">RTP LIMATOGEL</a>';
echo '<a class="data-m  nav-m" href="?page=data-keluaran-togel">Data Result</a>';
echo '<a class="data-m  nav-m" href="?page=paito-togel-warna">Paito Warna</a>';
echo '';
echo '<div class="accordion accordion-flush" id="menumobileac">';
echo '<div class="accordion-item bg-transparent">';
echo '<h2 class="accordion-header" id="flush-headingOne">';
echo '<a class="alat-m    nav-m" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">Alat Togel <i class="fas fa-chevron-circle-down"></i></a>';
echo '</h2>';
echo '<div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#menumobileac">';
echo '<div class="accordion-body">';
echo '<a class="alat-m  nav-m" href="?page=bbfs">BB Generator</a>';
echo '<a class="buku-mimpi-m  nav-m" href="?page=konversi-toto-sgp">Konv.Toto SGP</a>';
echo '<a class="buku-mimpi-m  nav-m" href="?page=buku-mimpi-togel">Buku Mimpi</a>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<a class="alat-m  nav-m" href="https://bocoran.limaangka.online/?page=bukti-jp-member" target="_blank">Bukti Jackpot</a>';
echo '<a class="alat-m active nav-m" href="?page=keluhan">Keluhan</a>';
echo '<a class="tour-m  nav-m" target="_blank" href="https://bocoran.limaangka.online/?page=panduan">Panduan</a>';
echo '';
echo '</div>';
echo '';
echo '';
echo '<div id="mains"> <!-- Main Body Nav -->';
echo '';
echo '<header>';
echo '';
echo '<div class="m-0 d-lg-none">';
echo '<div class="bg-wa">';
echo '<a target="_blank" href="https://api.whatsapp.com/send?phone=6287841008772"><h6 class="title-wa m-0"><i class="fab fa-whatsapp"></i> Whatsapp</h6></a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="top-nav">';
echo '<div class="container">';
echo '<div class="d-flex justify-content-center justify-content-lg-between">';
echo '';
echo '<div class="wrap-list">';
echo '<ul class="top-list">';
echo '<li>';
echo '<a target="_blank" href="https://cutt.ly/lima-apk"><img src="https://ik.imagekit.io/rwvgghdvd/LIMATOGEL/fav.png?updatedAt=1728374279114" class="icon-apk" alt="icon apk"> Download Aplikasi Togel </a>';
echo '</li>';
echo '<li><a target="_blank" href="https://cutt.ly/limatogel">Daftar Jadi Member</a></li>';
echo '<li><a target="_blank" href="https://t.me/Limatogellofficial"><i class="fab fa-telegram text-info"></i> Telegram</a></li>';
echo '<li><a target="_blank" href="https://secure.livechatenterprise.com/licence/16648860/v2/open_chat.cgi"><i class="fas fa-comments text-warning"></i> Livechat</a></li>';
echo '</ul>';
echo '</div>';
echo '';
echo '<div class="d-lg-block d-none">';
echo '';
echo '</div>';
echo '';
echo '';
echo '<div class="d-lg-block wa-desc d-none">';
echo '<div class="bg-wa rounded-bottom">';
echo '<a target="_blank" href="https://api.whatsapp.com/send?phone=6287841008772"><h6 class="title-wa m-0"><i class="fab fa-whatsapp"></i> Whatsapp</h6></a>';
echo '</div>';
echo '<p><i class="fas fa-clock"></i> <span id="Date"><span>xxxxx</span>, xx xxx xxxx</span> ( <span id="hours">00</span><span id="point">:</span><span id="min">00</span><span id="point">:</span><span id="sec">00</span> )</p>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="nav-bar d-none d-lg-block shadow">';
echo '<div class="container">';
echo '<!-- Navbar -->';
echo '<nav class="navbar navbar-expand-lg navbar-dark">';
echo '<div class="container-fluid">';
echo '<a style="margin-right: 7px !important;" class="navbar-brand" href="/">';
echo '<img src="https://ik.imagekit.io/rwvgghdvd/LIMATOGEL/logo.png?updatedAt=1728374275288" class="img-fluid d-block mx-auto" alt="logo blog ">';
echo '</a>';
echo '<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#menubar" aria-controls="menubarcontent" aria-expanded="false" aria-label="Toggle navigation">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '<div class="collapse navbar-collapse" id="menubar">';
echo '<ul class="navbar-nav me-auto mb-2 mb-lg-0">';
echo '<li class="nav-item">';
echo '<a class="nav-link';
echo '" aria-current="page" href="/"><i class="fas fa-home"></i> Home</a>';
echo '</li>';
echo '';
echo '<li class="nav-item">';
echo '<a class="nav-link " href="?page=livedraw-togel">Live draw</a>';
echo '</li>';
echo '';
echo '<li class="nav-item">';
echo '<a class="nav-link " href="?page=prediksi-togel">Prediksi Togel</a>';
echo '</li>';
echo '';
echo '<li class="nav-item position-relative">';
echo '<span class="position-absolute notify translate-middle badge rounded-pill bg-danger">';
echo '<span class="blinks"><i class="fas fa-fire"></i> HOT!</span>';
echo '</span>';
echo '<a class="nav-link " target="_blank" href="https://rtp-lima.com/lima">RTP LIMATOGEL</a>';
echo '</li>';
echo '';
echo '<li class="nav-item dropdown">';
echo '<a class="nav-link dropdown-toggle" href="#" id="menualattogel" role="button" data-bs-toggle="dropdown" aria-expanded="false">';
echo 'Alat Togel';
echo '</a>';
echo '<ul class="dropdown-menu" aria-labelledby="menualattogel">';
echo '<li><a class="dropdown-item" href="?page=jadwal-togel">Jadwal Togel</a></li>';
echo '<li><a class="dropdown-item" href="?page=bbfs">Bbfs Generator</a></li>';
echo '<li><a class="dropdown-item" href="?page=buku-mimpi-togel">Buku Mimpi</a></li>';
echo '<li><a class="dropdown-item" href="?page=paito-togel-warna">Paito Togel Warna</a></li>';
echo '<li><a class="dropdown-item" href="?page=konversi-toto-sgp">Konversi Toto SGP</a></li>';
echo '';
echo '';
echo '</ul>';
echo '</li>';
echo '';
echo '<li class="nav-item position-relative">';
echo '<span class="position-absolute notify translate-middle badge rounded-pill bg-danger">';
echo '<span class="blinks">NEW!</span>';
echo '</span>';
echo '<a class="nav-link " href="?page=data-keluaran-togel">Data Result</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link " href="https://bocoran.limaangka.online/?page=bukti-jp-member" target="_blank">Bukti Jackpot</a>';
echo '</li>';
echo '<li class="nav-item position-relative">';
echo '<span class="position-absolute notify translate-middle badge rounded-pill bg-danger">';
echo '<span class="blinks"><i class="fas fa-fire"></i> HOT!</span>';
echo '</span>';
echo '<a class="nav-link " target="_blank" href="https://limalangit.com/promotion">Promosi</a>';
echo '</li>';
echo '';
echo '<li class="nav-item">';
echo '<a class="nav-link active" href="?page=keluhan">Keluhan</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link " href="https://bocoran.limaangka.online/?page=panduan" target="_blank">Panduan</a>';
echo '</li>';
echo '</ul>';
echo '';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '';
echo '<!-- /Navbar -->';
echo '</div>';
echo '</div>';
echo '';
echo '</header>';
echo '';
echo '<div class="container">';
echo '<div class="main position-relative">';
echo '<button id="btn-up" class="btn btn-danger btn-up"><i class="fas fa-chevron-circle-up"></i></button>';
echo '';
echo '<div class="d-lg-none">';
echo '<div class="container">';
echo '';
echo '<div class="main navbar-ms border-bottom border-dark">';
echo '<div class="d-flex align-items-center justify-content-center">';
echo '<div>';
echo '<a href="/"><img class="img-fluid" src="https://ik.imagekit.io/rwvgghdvd/LIMATOGEL/logo.png?updatedAt=1728374275288" alt="logo blog mobile"></a>';
echo '</div>';
echo '';
echo '<!-- <div onclick="openMobilenav()" class="navbar-icons">';
echo '<i class="fas fa-bars"></i>';
echo '</div> -->';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="d-lg-none d-sm-block">';
echo '<div class="container p-3">';
echo '<div class="row g-2">';
echo '<div class="col-6">';
echo '<div class="d-grid">';
echo '<a href="/" class="btn btn-sm btn-warning">Home</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-6">';
echo '<div class="d-grid">';
echo '<a href="?page=livedraw-togel" class="btn btn-sm btn-warning">Livedraw</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-6">';
echo '<div class="d-grid">';
echo '<a href="?page=prediksi-mobile" class="btn btn-sm btn-warning">Prediksi Togel</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-6 d-none d-lg-block">';
echo '<div class="d-grid">';
echo '<a target="_blank" href="https://limalangit.com/promotion" class="btn btn-sm btn-warning">Promosi</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-6">';
echo '<div class="d-grid">';
echo '<a href="?page=jadwal-togel" class="btn btn-sm btn-warning">Jadwal Togel</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-6">';
echo '<div class="d-grid">';
echo '<a href="?page=data-keluaran-togel" class="btn btn-sm btn-warning">Data Result</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-6 d-none d-lg-block">';
echo '<div class="d-grid">';
echo '<a href="https://rtp-lima.com/lima" target="_blank" class="btn btn-sm btn-warning">Slot Gacor</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-6">';
echo '<div class="d-grid">';
echo '<a href="?page=bbfs" class="btn btn-sm btn-warning">BB Generator</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-6 d-none d-lg-block">';
echo '<div class="d-grid">';
echo '<a href="?page=paito-togel-warna" class="btn btn-sm btn-warning">Paito Warna</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-6 d-none d-lg-block">';
echo '<div class="d-grid">';
echo '<a href="?page=konversi-toto-sgp" class="btn btn-sm btn-warning">Konv.Toto SGP</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-6">';
echo '<div class="d-grid">';
echo '<a href="?page=buku-mimpi-togel" class="btn btn-sm btn-warning">Buku Mimpi</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-6">';
echo '<div class="d-grid">';
echo '<a href="https://bocoran.limaangka.online/?page=bukti-jp-member" target="_blank" class="btn btn-sm btn-warning">Bukti Jackpot</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-6 d-none d-lg-block">';
echo '<div class="d-grid">';
echo '<a href="?page=keluhan" class="btn btn-sm btn-warning">Keluhan</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-6 d-none d-lg-block">';
echo '<div class="d-grid">';
echo '<a href="https://bocoran.limaangka.online/?page=panduan" target="_blank" class="btn btn-sm btn-warning">Panduan</a>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="row">';
echo '';
echo '<!-- TitleBar -->';
echo '<div class="col-lg-12 order-lg-1 mb-2">';
echo '<div class="position-relative">';
echo '<div class="icon-teksberjalan">';
echo '<i class="fas fa-bullhorn text-secondary"></i>';
echo '</div>';
echo '<marquee class="text-uppercase" scrollamount="3" direction="left">LIMATOGEL BANDAR TOGEL ONLINE TERBESAR MENYEDIAKAN BOCORAN ANGKA JITU UNTUK LEBIH DARI 60 PASARAN RESMI BERHADIAH TERBESAR !!</marquee>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- /TitleBar -->';
echo '';
echo '';
echo '<!-- Mainbar -->';
echo '<div class="col-lg-12 order-lg-3 mb-3">';
echo '';
echo '<div class="row bg-mainslide p-2 justify-content-center">';
echo '<div class="col-lg-7">';
echo '<div class="swiper slider-blog">';
echo '<!-- Additional required wrapper -->';
echo '<div class="swiper-wrapper">';
echo '<!-- Slides -->';
echo '';
echo '<div class="swiper-slide">';
echo '<img data-src="https://ik.imagekit.io/rwvgghdvd/LIMATOGEL/MOBILE/PUASA%20LIMA.jpg?updatedAt=1741007770399" alt="slider 0" class="swiper-lazy rounded w-100" />';
echo '<div class="swiper-lazy-preloader"></div>';
echo '</div><div class="swiper-slide">';
echo '<img data-src="https://ik.imagekit.io/rwvgghdvd/LIMATOGEL/MOBILE/PROMO%20LIMA%20-%20WELCOME%20100%20VERSI%20MOBILE_0.jpg?updatedAt=1738829693263" alt="slider 1" class="swiper-lazy rounded w-100" />';
echo '<div class="swiper-lazy-preloader"></div>';
echo '</div><div class="swiper-slide">';
echo '<img data-src="https://ik.imagekit.io/rwvgghdvd/LIMATOGEL/LIMA-ROLLINGAN.jpg?updatedAt=1732611466874" alt="slider 2" class="swiper-lazy rounded w-100" />';
echo '<div class="swiper-lazy-preloader"></div>';
echo '</div><div class="swiper-slide">';
echo '<img data-src="https://ik.imagekit.io/rwvgghdvd/LIMATOGEL/togel(4).jpg?updatedAt=1728138150454" alt="slider 3" class="swiper-lazy rounded w-100" />';
echo '<div class="swiper-lazy-preloader"></div>';
echo '</div><div class="swiper-slide">';
echo '<img data-src="https://ik.imagekit.io/rwvgghdvd/LIMA-ALLPROMO.jpg?updatedAt=1730288732887" alt="slider 4" class="swiper-lazy rounded w-100" />';
echo '<div class="swiper-lazy-preloader"></div>';
echo '</div>';
echo '';
echo '</div>';
echo '<div class="swiper-pagination"></div>';
echo '</div>';
echo '';
echo '<div class="row g-1 my-2">';
echo '<div class="col d-grid">';
echo '<a target="_blank" href="https://cutt.ly/limatogel" class="btn btn-sm btn-warning"><i class="fas fa-sign-in-alt"></i> Login</a>';
echo '</div>';
echo '';
echo '<div class="col d-grid">';
echo '<a target="_blank" href="https://limalangit.com/promotion" class="btn btn-sm btn-primary"><i class="fas fa-hand-holding-usd"></i> Promo</a>';
echo '</div>';
echo '';
echo '<div class="col d-grid">';
echo '<a target="_blank" href="https://rtp-lima.com/lima" class="btn btn-sm btn-warning"><i class="fas fa-gamepad"></i> RTP Slot</a>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '</div>';
echo '';
echo '';
echo '<div class="col-lg-5 d-none d-lg-block">';
echo '<a href="https://limatogel.com/" target="_blank">  <img src="https://ik.imagekit.io/rwvgghdvd/LIMA-MAHJONG/PROMO%20LIMA/penambahan-promo-lima_02.jpg?updatedAt=1731322769046" class="img-fluid rounded" alt="bandar togel online"> </a>';
echo '';
echo '<a href="https://limatogel.com/" target="_blank">  <img src="https://ik.imagekit.io/rwvgghdvd/promo-lima-1-SET_03_0.jpg?updatedAt=1732612123111" class="img-fluid rounded" alt="bandar togel online"> </a>';
echo '';
echo '<a href="https://limatogel.com/" target="_blank">  <img src="https://ik.imagekit.io/rwvgghdvd/LIMA-MAHJONG/PROMO%20LIMA/penambahan-promo-lima_04.jpg?updatedAt=1731322769650" class="img-fluid rounded" alt="bandar togel online"> </a>';
echo '';
echo '<a href="https://limatogel.com/" target="_blank">  <img src="https://ik.imagekit.io/rwvgghdvd/LIMA-MAHJONG/PROMO%20LIMA/penambahan-promo-lima_05.jpg?updatedAt=1731322769030" class="img-fluid rounded" alt="bandar togel online"> </a>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<hr>';
echo '';
echo '<h6 class="text-center text-uppercase">INFO KELUHAN MEMBER SEPUTAR LIMATOGEL</h6>';
echo '<hr class="w-75 d-block mx-auto">';
echo '';
echo '<div class="row">';
echo '<div class="col-lg-6">';
echo '<div id="msg-keluhan"></div>';
echo '<form method="POST" id="ajukankeluhan">';
echo '<label class="my-2 text-uppercase"><i class="fas fa-info-circle"></i> Ajukan Keluhan</label>';
echo '<div class="input-group mb-3">';
echo '<span class="input-group-text" id="username"><i class="fas fa-user"></i></span>';
echo '<input type="text" name="username" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="username" required />';
echo '</div>';
echo '';
echo '<input type="hidden" name="kodekeluhan" value="38380fc4">';
echo '';
echo '<div class="input-group mb-3">';
echo '<span class="input-group-text" id="wakeluhan"><i class="fab fa-whatsapp"></i></span>';
echo '<input type="text" name="wakeluhan" class="form-control" placeholder="Nomor Wa aktif" aria-label="wakeluhan" aria-describedby="wakeluhan" />';
echo '</div>';
echo '';
echo '<div class="input-group mb-3">';
echo '<span class="input-group-text" id="keluhanjudul"><i class="fas fa-list"></i></span>';
echo '<input type="text" name="judulkeluhan" class="form-control" placeholder="Judul Keluhanmu" aria-label="keluhanjudul" aria-describedby="keluhanjudul" required />';
echo '</div>';
echo '';
echo '<textarea name="keluhanmsg" class="form-control" style="height: 250px;" placeholder="Isi pesan keluhanmu disini.." name="keluhanpesan"></textarea>';
echo '<div class="my-3 float-end">';
echo '<button type="submit" class="btn btn-sm btn-light"><i class="fas fa-paper-plane"></i> Kirim Keluhan</button>';
echo '</div>';
echo '</form>';
echo '</div>';
echo '';
echo '<div class="col-lg-6">';
echo '<form method="POST" id="showkeluhan">';
echo '<label class="my-2 text-uppercase"><i class="fas fa-info-circle"></i> Tampilkan Keluhan Sebelumnnya</label>';
echo '<div class="input-group mb-3">';
echo '<span class="input-group-text" id="kodekeluhan"><i class="fas fa-barcode"></i></span>';
echo '<input type="text" name="tampilkode" class="form-control" placeholder="Kode Keluhan" aria-label="kodekeluhan" aria-describedby="kodekeluhan" required />';
echo '<button type="submit" class="btn btn-sm btn-light"><i class="fas fa-search"></i></button>';
echo '</div>';
echo '';
echo '<!-- <div class="float-end">';
echo '<button type="submit" class="btn btn-sm btn-light"><i class="fas fa-eye"></i> Tampilkan</button>';
echo '</div> -->';
echo '</form>';
echo '';
echo '<div class="clearfix"></div>';
echo '';
echo '<div class="my-2">';
echo '<form id="inboxkeluhan" class="inboxkeluhan">';
echo '<h6><i class="fas fa-inbox"></i> Inbox Keluhan</h6>';
echo '<div class="chatbox rounded-top">';
echo '';
echo '<div id="chatboxes"></div>';
echo '';
echo '</div>';
echo '';
echo '<div class="input-group mt-1">';
echo '<input name="inboxkeluhan" placeholder="Ketik Pesan.." id="inboxmsgs" class="form-control" />';
echo '<button id="sendbtn" type="submit" class="btn btn-warning"><i class="fas fa-paper-plane"></i></button>';
echo '<div id="messagebox"></div>';
echo '<p class="bg-danger text-light p-1 my-2 rounded" id="textdisable"></p>';
echo '</div>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-12 my-3">';
echo '<hr class="d-block mx-auto w-75"/>';
echo '<p>Halaman Keluhan Seo disini</p>        </div>';
echo '</div>';
echo '</div>';
echo '<!-- /Mainbar -->';
echo '';
echo '';
echo '<!-- Sidebar -->';
echo '<!-- <div class="col-lg-3 order-lg-2 mb-3">';
echo '<img src="images/slotgif.gif" width="230" alt="">';
echo '<hr>';
echo '<div id="rtpslot"></div>';
echo '';
echo '<div id="dindongwrap">';
echo '<img src="images/dindo.gif" class="img-fluid title-img">';
echo '<div class="my-2" id="dindong-game"><img src="images/loading.gif" width="50" alt="loading"> </div>';
echo '</div>';
echo '';
echo '</div> -->';
echo '<!-- /Sidebar -->';
echo '';
echo '<div class="col-lg-12 order-lg-3">';
echo '<hr class="w-75 d-block mx-auto" />';
echo '<h1 class="ql-align-center"><strong>Daftar Situs Judi Online Slot Gacor</strong></h1><p class="ql-align-center">Situs Prediksi Togel Terbaik dan Terlengkapp</p><p class="ql-align-justify"><strong><a href="https://limatogel.com/" rel="noopener noreferrer" target="_blank">LIMATOGEL</a></strong> Menyediakan sebuah aplikasi judi togel online terbaik dengan fitur fitur pilihan terbaik seperti alat prediksi dan data pengeluaran result togel terupdate. Dengan berbagai pilihan aplikasi resmi kami ini sangat memudahkan para bettor untuk memainkan tebak angka saat ingin melakukan prediksi ataupun bocoran.</p><p class="ql-align-justify">Selain aplikasi untuk game togel online, LIVEDRAW GROUP juga menyediakan bocoran RTP GACOR dengan persentase kemenangan tertinggi di banding dengan situs / bandar slot lainnya.</p><table><tbody><tr><td data-row="1"><strong class="ql-color-#fcfcfd">Pilihan Layanan Deposit</strong></td><td data-row="1"><span class="ql-color-#fcfcfd">🏅 Transfer Bank, Gopay, OVO, Linkaja, QRIS Barcode, dan DANA</span></td></tr><tr><td data-row="2"><strong class="ql-color-#fcfcfd">Minimal Deposit</strong></td><td data-row="2"><span class="ql-color-#fcfcfd">💰 Rp 10.000</span></td></tr><tr><td data-row="3"><strong class="ql-color-#fcfcfd">Minimal Withdraw</strong></td><td data-row="3"><span class="ql-color-#fcfcfd">💰 Rp 25.000</span></td></tr><tr><td data-row="4"><strong class="ql-color-#fcfcfd">Game Slot Gacor</strong></td><td data-row="4"><span class="ql-color-#fcfcfd">🔱 Gates Of Olympus, Mahjong Ways, Koi Gate</span></td></tr><tr><td data-row="5"><strong class="ql-color-#fcfcfd">Kecepatan Deposit</strong></td><td data-row="5"><span class="ql-color-#fcfcfd">🀄️ ± 1 Menit</span></td></tr><tr><td data-row="6"><strong class="ql-color-#fcfcfd">Kecepatan Withdraw</strong></td><td data-row="6"><span class="ql-color-#fcfcfd">🀄️ ± 2 Menit</span></td></tr></tbody></table><p class="ql-align-center"> </p>        </div>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<footer class="text-center text-light py-3">';
echo '<div class="container d-flex justify-content-center">';
echo '<p>Copyright &copy; <p class="mx-1">2025</p><p><a href="https://limatogel.com" rel="noopener noreferrer" target="_blank">LIMATOGEL</a></p></p>';
echo '</div>';
echo '</footer>';
echo '';
echo '</div> <!-- /Main Body Nav -->';
echo '';
echo '<!-- Kontak aktif -->';
echo '<div class="modal fade" id="kontakus" tabindex="-1" aria-labelledby="kontaklabel" aria-hidden="true">';
echo '<div class="modal-dialog">';
echo '<div class="modal-content">';
echo '<div class="modal-header">';
echo '<h5 class="modal-title" id="kontaklabel"><i style="font-size: 0.9rem;" class="fas bg-danger text-light rounded-circle p-2 fa-phone-alt"></i> Hubungi Kami:</h5>';
echo '</div>';
echo '<div class="modal-body">';
echo '<p>WA : 6287841008772</p>      </div>';
echo '<div class="modal-footer">';
echo '<button type="button" class="btn btn-danger" data-bs-dismiss="modal"><i class="fas fa-check"></i> Selesai</button>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div><script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>';
echo '<script src="js/bootstrap.min.js"></script>';
echo '<script src="js/owl.carousel.js"></script>';
echo '<script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>';
echo '<script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>';
echo '<script src="js/jquery.easing.min.js"></script>';
echo '<script src="js/jquery.easy-ticker.js"></script>';
echo '<script src="js/pagination.min.js"></script>';
echo '<script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>';
echo '<script src="js/blog-tgel.js"></script>';
echo '<script>';
echo '</script></body>';
echo '</html>';
echo '';
echo '';
echo '';
echo '';
echo '<!-- LIMATOGEL COPYRIGHT -->';
?>